
    CREATE TABLE IF NOT EXISTS "solicitud_de_soporte_general" (
        "id" BIGSERIAL PRIMARY KEY,
        "airtable_id" TEXT UNIQUE,
    "fecha_de_la_incidencia_o_solicitud" DATE,
    "servicio" TEXT,
    "clientes_aromatex" JSONB,
    "nombre_del_cliente_from_clientes_aromatex" JSONB,
    "tipo_de_incidencia" TEXT,
    "ubicacin_propiedad" TEXT,
    "detalles_de_las_incidencia_solicitud" TEXT,
    "status" TEXT,
    "quien_reporta" TEXT,
    "correo_electrnico" TEXT,
    "contacto_cliente" TEXT,
    "telefono_cliente" TEXT,
    "correo_del_contacto" TEXT,
    "evidencia" JSONB,
    "fecha_de_solucion" DATE,
    "queja_en_operandium" BOOLEAN,
    "creada" TIMESTAMPTZ,
    "comentarios_operaciones" TEXT,
    "zona" TEXT,
    "id" SERIAL,
    "evaluacin_de_aroma" JSONB,
    "mes" TEXT,
    "seguimiento_operaciones" TEXT,
    "incidencias_elektra" JSONB,
    "fecha_compromiso" DATE,
    "responsable" TEXT,
    "plaga_encontrada" TEXT,
    "tiempo_de_respuesta" TEXT,
    "sub_motivo" TEXT,
    "acr" TEXT,
    "resumen_de_evidencia_evidencia" TEXT,
    "incidencias_camino_real" TEXT
    );
    